import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className="py-10 bg-teal-300 text-center">
        <h1 className="text-4xl text-red-500">Hello Tailwind CSS</h1>
      </div>
    </>
  )
}

export default Home;